name: suvidha_app_ui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  get_storage: ^2.0.3
  sizer: ^2.0.15
  velocity_x: ^3.4.0
  font_awesome_flutter: ^10.1.0
  #permission_handler: ^9.2.0
  lottie: ^1.3.0
  http: ^0.13.4
  #http: ^1.1.0
  flutter_carousel_slider: ^1.0.8
  get: ^4.6.5
  intl: ^0.17.0
  url_launcher: ^6.1.4
  flutter_phone_direct_caller: ^2.1.1
  flutter_launch: ^0.3.0
  razorpay_flutter:

  video_player: ^2.4.4
  chewie: ^1.3.3
  #splashscreen:
  share_plus: ^7.1.0
  google_fonts:
  image_picker: ^0.8.6
  flutter_inappwebview:
  sms_autofill:
  #file_picker:

  webview_flutter:
  flutter_launcher_icons: ^0.12.0
  file_picker: ^5.3.1
  flutter_otp_text_field: ^1.1.1
  otp_text_field: ^1.1.3
  timer_count_down:
  pin_code_fields: ^8.0.1
  fl_chart: ^0.62.0
  graphic: ^2.2.1
  lite_rolling_switch: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/video/suvidha33logo.jpeg"
  #image_path_android: "android/assetss/imagess/logo.jpg"
  #image_path_ios: "assetts/images/ios/logo.jpg"


  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - lib/assets/
    - lib/assets/video/
    - lib/assets/video/suvidha33logo.jpeg

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
