import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'YourLanguages': 'Your Selected Language is :-',
          'language': 'English',
          'New Connection Services': 'New Connection Services',
          'My Connection': 'My Connection',
          'Services for existing Consumers': 'Services for existing Consumers',
          'Billing & Payment Services': 'Billing & Payment Services',
          'Solar Rooftop Services': 'Solar Rooftop Services',
          'Other Services': 'Other Services',
          'Bill On Miss Call': 'Bill On Miss Call',
          'Customer Care 1912': 'Customer Care 1912',
          'Report Electricity Theft': 'Report Electricity Theft',
          'Consumer Grievance': 'Consumer\nGrievance',
          'Bill Generated Self Service': 'Bill Generated Self Service',
          'Bill & Payment Service': 'Bill & Payment Service',
          'Smart Meter Services': 'Smart Meter Services',
          'Apply New Connection for Solar Rooftop':
              'Apply New Connection for Solar Rooftop',
          'Apply For Solar Rooftop NetMatering':
              'Apply For Solar Rooftop NetMatering',
          'Update Email & Mobile': 'Update Email & Mobile',
          'Address Correction': 'Address Correction',
          'Load Change': 'Load Change',
          'Apply Disconnection': 'Apply Disconnection',
          'Go Green/E-Bill': 'Go Green/E-Bill',
          'Refund Security Deposite': 'Refund Security Deposite',
        },
        'hi_IN': {
          'YourLanguages': 'आपकी चयनित भाषा है:-',
          'language': 'हिन्दी',
          'New Connection Services': 'नई कनेक्शन सेवाएँ',
          'My Connection': 'मेरे कनेक्शन',
          'Services for existing Consumers': 'मौजूदा उपभोक्ताओं के लिए सेवाएँ',
          'Billing & Payment Services': 'बिलिंग एवं भुगतान सेवाएँ',
          'Solar Rooftop Services': 'सौर छत सेवाएँ',
          'Other Services': 'अन्य सेवाएं',
          'Bill On Miss Call': 'मिस कॉल पर बिल',
          'Customer Care 1912': 'ग्राहक सेवा 1912',
          'Report Electricity Theft': 'बिजली चोरी की रिपोर्ट करें',
          'Consumer Grievance': 'उपभोक्ता शिकायत',
          'Bill Generated Self Service': 'बिल जनित स्वयं सेवा',
          'Bill & Payment Service': 'बिल एवं भुगतान सेवा',
          'Smart Meter Services': 'स्मार्ट मीटर सेवाएँ',
          'Apply New Connection for Solar Rooftop':
              'सोलर रूफटॉप के लिए नया कनेक्शन लागू करें',
          'Apply For Solar Rooftop NetMatering':
              'सोलर रूफटॉप नेटमैटरिंग के लिए आवेदन करें',
          'Update Email & Mobile': 'ईमेल और मोबाइल अपडेट करें',
          'Address Correction': 'पता सुधार',
          'Load Change': 'लोड परिवर्तन',
          'Apply Disconnection': 'विच्छेदन लागू करें',
          'Go Green/E-Bill': 'गो ग्रीन/ई-बिल',
          'Refund Security Deposite': 'सुरक्षा जमा राशि वापस करें',
        },
        'bho_IN': {
          'YourLanguages': 'राउर चुनल भाषा बा :-',
          'language': 'भोजपुरी',
          'New Connection Services': 'नया कनेक्शन सेवा के बारे में बतावल गइल',
          'My Connection': 'हमार कनेक्शन बा',
          'Services for existing Consumers': 'मौजूदा उपभोक्ता खातिर सेवा',
          'Billing & Payment Services':
              'बिलिंग अउर भुगतान सेवा के बारे में बतावल गइल बा',
          'Solar Rooftop Services': 'सौर छत पर सेवा के सुविधा दिहल जाला',
          'Other Services': 'अन्य सेवा के बारे में बतावल गइल बा',
          'Bill On Miss Call': 'बिल ऑन मिस कॉल के बा',
          'Customer Care 1912': 'ग्राहक देखभाल 1912 के बा',
          'Report Electricity Theft': 'बिजली चोरी के रिपोर्ट करीं',
          'Consumer Grievance': 'उपभोक्ता के शिकायत बा',
          'Bill Generated Self Service': 'बिल से जनरेट कइल गइल स्वयंसेवी सेवा',
          'Bill & Payment Service':
              'बिल अउर भुगतान सेवा के बारे में बतावल गइल बा',
          'Smart Meter Services': 'स्मार्ट मीटर सेवा के बारे में बतावल गईल बा',
          'Apply New Connection for Solar Rooftop':
              'सोलर रूफटॉप खातिर नया कनेक्शन लागू करीं',
          'Apply For Solar Rooftop NetMatering':
              'सोलर रूफटॉप नेटमेटरिंग खातिर आवेदन करीं',
          'Update Email & Mobile': 'ईमेल अउर मोबाइल के अपडेट करीं',
          'Address Correction': 'पता सुधारल जा सकेला',
          'Load Change': 'लोड चेंज के बा',
          'Apply Disconnection': 'डिस्कनेक्ट के लागू करीं',
          'Go Green/E-Bill': 'ग्रीन/ई-बिल जाओ',
          'Refund Security Deposite': 'वापसी सुरक्षा जमा के बा',
        },
        'mai_IN': {
          'YourLanguages': 'अहाँक चयनित भाषा अछि ',
          'language': 'मैथिली',
          'New Connection Services': 'नए कनेक्शन सेवाएँ',
          'My Connection': 'हमर कनेक्शन',
          'Services for existing Consumers': 'मौजूदा उपभोक्ता के लिये सेवाएँ',
          'Billing & Payment Services': 'बिलिंग एवं भुगतान सेवाएँ',
          'Solar Rooftop Services': 'सौर छत सेवा',
          'Other Services': 'अन्य सेवाएँ',
          'Bill On Miss Call': 'मिस कॉल पर बिल',
          'Customer Care 1912': 'ग्राहक देखभाल 1912',
          'Report Electricity Theft': 'बिजली चोरी के रिपोर्ट करू',
          'Consumer Grievance': 'उपभोक्ता शिकायत',
          'Bill Generated Self Service': 'बिल उत्पन्न स्वयंसेवी सेवा',
          'Bill & Payment Service': 'बिल एवं भुगतान सेवा',
          'Smart Meter Services': 'स्मार्ट मीटर सेवा',
          'Apply New Connection for Solar Rooftop':
              'सोलर रूफटॉप के लिये नया कनेक्शन लागू करे',
          'Apply For Solar Rooftop NetMatering':
              'सौर छत पर नेटमेटरिंग के लिये आवेदन करे ',
          'Update Email & Mobile': 'ईमेल एवं मोबाइल अपडेट करें',
          'Address Correction': 'पता सुधार',
          'Load Change': 'लोड परिवर्तन',
          'Apply Disconnection': 'डिस्कनेक्ट लागू करू',
          'Go Green/E-Bill': 'ग्रीन/ई-बिल जाउ',
          'Refund Security Deposite': 'वापसी सुरक्षा जमा',
        }
      };
}
